- defaultTab: nodes
  description: 資産取得
  executionEnabled: true
  id: b107f6b9-f177-4413-8745-038bd7f306cd
  loglevel: INFO
  name: asset
  nodeFilterEditable: false
  schedule:
    dayofmonth:
      day: 1/1
    month: '*'
    time:
      hour: 0/1
      minute: '0'
      seconds: '0'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - description: asset
      exec: /home/tsu-nera/repo/bakuchi/bin/asset-bot.sh
    keepgoing: false
    strategy: node-first
  uuid: b107f6b9-f177-4413-8745-038bd7f306cd
