import src.env as env

TICK_INTERVAL_SEC = 1

EXCHANGE_ID_BITFLYER = "bitflyer"
EXCHANGE_ID_COINCHECK = "coincheck"
EXCHANGE_ID_LIQUID = "liquid"
EXCHANGE_ID_BITBANK = "bitbank"
EXCHANGE_ID_BITMEX = "bitmex"
EXCHANGE_ID_BITMEX_DEMO = "bitmex_demo"
EXCHANGE_ID_GEMINI_DEMO = "gemini_demo"

# 現在対応している取引所
EXCHANGE_ID_LIST = [EXCHANGE_ID_COINCHECK, EXCHANGE_ID_LIQUID]

SYMBOL_BTC_JPY = "BTC/JPY"
SYMBOL_BTC_USD = "BTC/USD"

API_KEY = "apiKey"
API_SECRET = "apiSecret"

EXCHANGE_AUTH_DICT = {
    EXCHANGE_ID_BITFLYER: {
        API_KEY: env.BITFLYER_API_KEY,
        API_SECRET: env.BITFLYER_API_SECRET
    },
    EXCHANGE_ID_COINCHECK: {
        API_KEY: env.COINCHECK_API_KEY,
        API_SECRET: env.COINCHECK_API_SECRET
    },
    EXCHANGE_ID_LIQUID: {
        API_KEY: env.LIQUID_API_KEY,
        API_SECRET: env.LIQUID_API_SECRET
    },
    EXCHANGE_ID_BITBANK: {
        API_KEY: env.BITBANK_API_KEY,
        API_SECRET: env.BITBANK_API_SECRET
    },
    EXCHANGE_ID_BITMEX: {
        API_KEY: env.BITMEX_API_KEY,
        API_SECRET: env.BITMEX_API_SECRET
    },
    EXCHANGE_ID_BITMEX_DEMO: {
        API_KEY: env.BITMEX_TESTNET_API_KEY,
        API_SECRET: env.BITMEX_TESTNET_API_SECRET
    },
    EXCHANGE_ID_GEMINI_DEMO: {
        API_KEY: env.GEMINI_SANDBOX_API_KEY,
        API_SECRET: env.GEMINI_SANDBOX_API_SECRET
    }
}

ORDER_TYPE_LIMIT = "limit"  # 指値注文
ORDER_TYPE_MARKET = "market"  # 成功注文
ORDER_SIDE_BUY = "buy"
ORDER_SIDE_SELL = "sell"
